#!/usr/bin/env perl

use 5.16.0;
use warnings;

my $file = shift;
open my $fh, '>', $file;
my $yml = <<'YML';
---
description: A Delicious beverage of frew's own design
name: Frewba Libre
source: TV Guide wtf?
variant_of_drink: Cuba Libre
YML
print $fh $yml;
close $fh;
