#!/usr/bin/env perl

use 5.16.1;
use warnings;

my $file = shift;
open my $fh, '>', $file;
my $recipe = <<'RECIPE';
Blood Wallet

This is a thing from a song by Godspeed! You Black Emperor.

I'm not actually much of a fan.

 * 1 ounce of Wallet
 * 2 tablespoons of Blood
 # Non-human, plz

Source: my brain, sector 5
RECIPE
print $fh $recipe;
close $fh;
