#!/usr/bin/env perl

use 5.16.1;
use warnings;

my $file = shift;
open my $fh, '>', $file;
my $yml = <<'YML';
---
name: Awesome bevvy
description: YUMM
source: Boy's Life
ingredients:
  -
    name: ice
    unit: ounce
    amount: 4
YML
print $fh $yml;
close $fh;
